# fly.toml app configuration file generated for moiniorell on 2024-02-20T20:17:08+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moiniorell'
primary_region = 'ams'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
